openapi: "3.0.0"
info: 
  title: "OpenAPI Sprecification - Exercise 2"
  version: "3.3.3"
servers: 
  - url: "http://localhost:8000"
    description: Server
paths: 
  /ingredients:
    get:
      description: Get all ingredients
      responses:
        '200':
          description: Ingredients Lists
          content:
            application/json:
              schema: 
                type: array
                items:
                  $ref: '#/components/schemas/Ingredients'
                example: 
                  Laitue: 
                    id: 1
                    name: Laitue
                    price: 800
                    ingredientCategory: VEGETABLE
                  Tomate: 
                    id: 2
                    name: Tomate
                    price: 600
                    ingredientCategory: VEGETABLE
                  Poulet: 
                    id: 3
                    name: Poulet
                    price: 4500
                    ingredientCategory: ANIMAL 
                  Chocolat:
                    id: 4
                    name: Chocolat 
                    price: 3000
                    ingredientCategory: OTHER
                  Beurre:
                    id: 5
                    name: Beurre
                    price: 2500
                    ingredientCategory: DAILY
  /ingredients/{id}:
    get: 
      description: Find ingredient by Id 
      parameters:
        - name: id
          in : path 
          required: true
          schema: 
            type: integer
      responses:
        '200':
          description: Ingredient by Id
          content: 
            application/json:
              schema:
                type: array
                items: 
                  $ref: "#/components/schemas/Ingredients"
        '404':
          description: Ingredient not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                message: Ingredient.id={id) is not found
                code: 404
  /ingredients/{id}/stock:
              
    get: 
      description: Found ingredient by stock
      parameters: 
        - name: id
          in: path
          required: true
          schema:
            type: integer
        - name: at
          in : query
          description: stock date time
          required: true
          schema: 
            type: string
            format: date-time
        - name: unit
          in: query 
          description: stock unit
          required: true
          schema: 
            type: string
            enum: 
              - PCS 
              - KG 
              - L
      responses:
        '200':
          description: Ingredient by stock
          content: 
            application/json:
              schema:
                $ref: "#/components/schemas/Ingredients"
        '404':
          description: Ingredient not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                message: Ingredient.id={id) is not found
                code: 404
        '400':
          description: Bad request, time or unit are required
          content: 
            application/json:
              schema:
                $ref: "#components/schemas/Error"
              example: 
                message: Either mandatory query parameter `at` or `unit` is not provided
                code: 400
  /dish:
    get:
      description: getAllDishes
      responses: 
        '200':
          description: list of dishes with all ingredients
          content: 
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Dish'
                example: 
                  id: 1
                  name: Salade Fraîche
                  type: STARTER
                  ingredient: 
                    Laitue: 
                      
        
  /dish/{id}:
    put: 
      description: Modify the list of ingredient in dish
      parameters:
        - name: id
          in: path
          required: true
          schema: 
            type: integer
      requestBody:
         description: associate or dissociate dish Ingredient
         content: 
          application/json:
            schema: 
              $ref: "#/components/schemas/Ingredients"
            example:
              Laitue:
                id: 1
                name: Laitue
                price: 800
                ingredientCategory: VEGETABLE
              Oignon:
                id: 3
                name: Oignon
                price: 800
                ingredientCategory: VEGETABLE
              
      responses: 
        '200':
          description: Ingredients updated
          content: 
            application/json: 
              schema: 
                $ref: "#/components/schemas/Dish"
                example:
                  Laitue:
                    id: 1
                    name: Laitue
                    price: 800
                    ingredientCategory: VEGETABLE
                  Oignon:
                    id: 3
                    name: Oignon
                    price: 800
                ingredientCategory: VEGETABLE
        '400':
          description: Ingredient required
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                message: an ingredient is required for dish {id}
                code: 400
        '404':
          description: Ingredient not found
          content: 
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                message: “Dish.id={id} is not found”
                code: 404

components: 
  schemas:
      Ingredients: 
        required:
         - id
         - name
         - price
         - ingredientsCategory
        properties:
          id: 
            type: integer
            format: byte64
            example: 1
          name: 
            type: string
            example: Laitue
          price: 
            type: number
            example : 800
          ingredientCategory:
            type: string
            enum: 
              - VEGETABLE
              - ANIMAL 
              - MARINE 
              - DAIRY 
              - OTHER
      Error:
        type: object 
        required: 
        - message
        - code 
        properties:
          message: 
            type: string   
          code:
            type: integer
      Dish: 
        required:
          - id
          - name
          - price
          - ingredients
        properties:
          id:
            type: integer
            format: byte64
          name:
            type: string
            example: Salade Fraîche
          price: 
            type: number
          ingredient:
            type: array
            items:
              $ref: "#/components/schemas/Ingredients"
           
             
          
            


          


        
      


    
                  
                    




